---
- name: Tomcat deployment playbook
  hosts: appserver     # Inventory hosts group / server to act on
  become: yes             
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
  roles:
    - tomcat